# Generated by Django 2.2.3 on 2019-08-10 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='buissness_name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='buissness_type',
            new_name='business_type',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 10, 7, 38, 56, 9968, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
